### ISSUE TITLE
Inconsistencies in formatting within braces

### ISSUE THREAD

**Issue by stinos** [davidvarga/MBeautifier#55]
The latest version with default settings produces this output:
```
length(x) + 1;
a(length(x)+1);

a(b:b+n-1);
b + n - 1;
```
So the sameexpressions gets formatted in different ways depending on where it appears. This was not the case in older versions; is this by design now?

**Comment by davidvarga** [comment]
It is by design now, controlled by the "MatrixIndexing_ArithmeticOperatorPadding" special rule. This rule defaults to "0", that means that arithmetic operators will be not padded by white-spaces used for indexing matrices (there is a similar one used for cell arrays "CellArrayIndexing_ArithmeticOperatorPadding").

If you set these rules to 1 in the configuration XML, then execute "MBeautify.setup" they will be formatted in the same way (maybe you have to execute "clear classes" to force Matlab to reload the classes).

**Comment by stinos** [comment]
Oh ok. I quicly scanned through the commits but did miss this. All good now. And thanks for this piece of software btw.
