### ISSUE TITLE
New setting: Inlining continous lines

### ISSUE THREAD

**Issue by davidvarga** [davidvarga/MBeautifier#58]
New setting to inline continous lines (...). Possibly with subrules (inline arrays and matrices is a special case).

**Comment by davidvarga** [comment]
Implemented, by default it is disabled.

**Comment by kupiqu** [comment]
This option does not seem to work for me. I'll try to reproduce in a simpler example and will attach here.

**Comment by kupiqu** [comment]
An example:
```
x = ...
    2;
```
After setting InlineContinousLines to 1 in MBeautyConfigurationRules.xml, I would expect:
```
x = 2;
```
But instead nothing changes.

Is this a bug or did I understand this feature wrong?

**Comment by davidvarga** [comment]
Seems to work for me? If you edit the XML file you have to call `MBeautify.setup()` to apply the changes you made in the XML file.

**Comment by kupiqu** [comment]
> ... you have to call MBeautify.setup() to apply the changes...

Oops, I missed that point

**Comment by kupiqu** [comment]
It works, thank you!

For the case it is useful, I noticed a minor issue:

``` 
|| ...
    some_code
```

is converted to 

```
 ||some_code
```

instead of

```
 || some_code
```

**Comment by davidvarga** [comment]
Hm, I will check this out :)

**Comment by kupiqu** [comment]
> Hm, I will check this out :) Could you give more context to the code? Thanks

My issue is in the context of an if:
```
if some_long_condition || ...
    some_other_long_condition || ...
    yet_another
 ```

the result becomes:
```
if some_long_condition ||some_other_long_condition ||yet_another
 ```

i.e., there is no whitespace after `||`

I guess this happens when removing `...`, which removes all extra whitespace around it. This is fine most of the time, but not always.

My impression is that, instead of trying to fix for all possible conditions in which this is not done properly (which can be tricky), the easiest fix would be to just prioritize inlining continous lines when enabled, so that these rules are the first to be applied. Then the other rules would easily fix the missing whitespace in the places there is need to.

**Comment by davidvarga** [comment]
Fixed it - now it is formatted properly while taking the other inlining rules into account too.

**Comment by kupiqu** [comment]
Thank you
